import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { jsPDF } from "jspdf";
import logo from '../../pictures/logo.png'; // Adjust the path to your logo image
import "./addusr.css";

function AddUser(props) {
  const { _id, userid, name, email, age, address, userrole, password } = props.user;
  const [isDeleting, setIsDeleting] = useState(false);
  const navigate = useNavigate();

  const deleteHandler = async () => {
    if (window.confirm("Are you sure you want to delete this user?")) {
      setIsDeleting(true);
      try {
        const response = await axios.delete(`http://localhost:5000/users/${_id}`);
        
        if (response.data.success) {
          props.onUserDelete && props.onUserDelete(_id);
          setTimeout(() => {
            window.location.reload();
          }, 5);
        } else {
          alert(response.data.message || "Failed to delete user");
        }
      } catch (error) {
        console.error("Delete error:", error);
        alert(error.response?.data?.message || "Error deleting user");
      } finally {
        setIsDeleting(false);
      }
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Add Logo
    doc.addImage(logo, 'PNG', 20, 10, 40, 20); // Position: x=20, y=10, width=40mm, height=20mm
    
    // Company Header (shifted down to avoid overlap with logo)
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("SMN Construction", 20, 40);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Address: 1340 Shrewsbury Parkway, Srilanka", 20, 48);
    doc.text("Email: SMN@construction.com", 20, 54);
    doc.text("Phone: +94 77 1793510", 20, 60);
    
    // Right-aligned Report Generated Date with current date
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.setFontSize(10);
    doc.text(`Report Generated: ${currentDate}`, 150, 40);

    // Horizontal Line
    doc.setLineWidth(0.5);
    doc.line(20, 65, 190, 65);

    // Title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("User Details", 20, 75);

    // User Details in a Table-like Structure
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Field", 20, 90);
    doc.text("Details", 80, 90);

    doc.setLineWidth(0.2);
    doc.line(20, 92, 190, 92); // Table header underline

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    
    const userDetails = [
      { field: "User ID", value: userid },
      { field: "Name", value: name },
      { field: "Email", value: email },
      { field: "Age", value: age.toString() },
      { field: "Address", value: address },
      { field: "User Role", value: userrole },
    ];

    let yPosition = 100;
    userDetails.forEach((detail) => {
      doc.text(detail.field, 20, yPosition);
      doc.text(detail.value, 80, yPosition);
      yPosition += 10;
    });

    // Footer
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by SMN Construction Management System", 20, 280);
    doc.text("Page 1 of 1", 170, 280);

    doc.save(`${name}_UserDetails.pdf`);
  };

  return (
    <tr className="add-user-table-row">
      <td className="add-user-table-cell">{userid}</td>
      <td className="add-user-table-cell">{name}</td>
      <td className="add-user-table-cell">{email}</td>
      <td className="add-user-table-cell">{age}</td>
      <td className="add-user-table-cell">{address}</td>
      <td className="add-user-table-cell">{userrole}</td>
      <td className="add-user-table-cell">
        <Link to={`/userdetails/${_id}`}>
          <button className="add-user-button-update">Update</button>
        </Link>
        <button 
          className="add-user-button-delete" 
          onClick={deleteHandler}
          disabled={isDeleting}
        >
          {isDeleting ? "Deleting..." : "Delete"}
        </button>
        <button 
          className="add-user-button-download"
          onClick={downloadPDF}
        >
          Download PDF
        </button>
      </td>
    </tr>
  );
}

export default AddUser;